!!es.um.poa.scenarios.ScenarioConfig
name: "EscenarioEjemplo"
description: "Ejemplo para hacer una configuración YAML"
fishMarket:
  name: "Lonja"
  config: "configs/fishMarket.yaml"
buyers:
  - name: "Comprador1"
    config: "configs/buyerType1.yaml"