!!es.um.poa.scenarios.ScenarioConfig
name: "EscenarioEjemplo"
description: "Ejemplo para hacer una configuración YAML"
fishMarket:
  name: "Lonja"
  config: "configs/fishMarket.yaml"
buyers:
  - name: "Comprador1"
    config: "configs/buyerType1.yaml"
  - name: "Comprador2"
    config: "configs/buyerType1.yaml"
sellers:
  - name: "Vendedor1"
    config: "configs/sellerType1.yaml"
  - name: "Vendedor2"
    config: "configs/sellerType1.yaml"
fishShips:
   - name: "Barco Pesquero1"
     config: "configs/fishShipType1.yaml"
   - name: "Barco Pesquero2"
     config: "configs/fishShipType2.yaml"